//> using scala "3.2"
//> using jvm "system"
//> using deps "org.scalameta::munit::1.0.0-M7"
//> using deps "com.lihaoyi::os-lib::0.9.1"
//> using deps "com.lihaoyi::cask::0.9.0"
//> using deps "com.lihaoyi::scalatags::0.11.1"
//> using repository "central"
//> using repository "https://maven.aliyun.com/repository/public/"
